/* eslint-disable prettier/prettier */

// Authentication
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';


// Signupscreens navigation
export const SCREEN1 = 'SCREEN1';
export const SCREEN2 = 'SCREEN2';
export const SCREEN3 = 'SCREEN3';

// Chatscreen
export const OPEN_CHAT = 'OPEN_CHAT';
export const SET_DEFAULT_ROUTE = 'SET_DEFAULT_ROUTE';

// HomeScreen
export const SHOW_DETAILS = 'SHOW_DETAILS';

// Profile
export const SET_FIRST_SCREEN_DETAIL = 'SET_FIRST_SCREEN_DETAIL';
export const SET_SECOND_SCREEN_DETAIL = 'SET_SECOND_SCREEN_DETAIL';
export const SET_THIRD_SCREEN_DETAIL = 'SET_THIRD_SCREEN_DETAIL';

//General Reducer
export const LOADING = 'LOADING';
export const SHOW_CARDS = 'SHOW_CARDS';
export const SHOW_SEARCHCARDS = 'SHOW_SEARCHCARDS';
export const INDEX = 'INDEX';
export const SEARCH_INDEX = 'SEARCH_INDEX';
export const LARGE_CARD_DATA = 'LARGE_CARD_DATA';

//Reset attribute
export const RESET_ATTRIBUTE_ONE = 'RESET_ATTRIBUTE_ONE';
export const RESET_ATTRIBUTE_TWO = 'RESET_ATTRIBUTE_TWO';
export const RESET_ATTRIBUTE_THREE = 'RESET_ATTRIBUTE_THREE';
export const RESET_ATTRIBUTE_FOUR = 'RESET_ATTRIBUTE_FOUR';
export const RESET_ATTRIBUTE_FIVE = 'RESET_ATTRIBUTE_FIVE';
export const RESET_ATTRIBUTE_SIX = 'RESET_ATTRIBUTE_SIX';
export const RESET_ATTRIBUTE_SEVEN = 'RESET_ATTRIBUTE_SEVEN';
export const RESET_ATTRIBUTE_EIGHT = 'RESET_ATTRIBUTE_EIGHT';

export const SET_ATTRIBUTE_FIRST = 'SET_ATTRIBUTE_FIRST';
export const SET_ATTRIBUTE_SECOND = 'SET_ATTRIBUTE_SECOND';
export const SET_ATTRIBUTE_THIRD = 'SET_ATTRIBUTE_THIRD';
export const SET_ATTRIBUTE_FOURTH = 'SET_ATTRIBUTE_FOURTH';
export const SET_ATTRIBUTE_FIFTH = 'SET_ATTRIBUTE_FIFTH';
export const SET_ATTRIBUTE_SIXTH = 'SET_ATTRIBUTE_SIXTH';
export const SET_ATTRIBUTE_SEVENTH = 'SET_ATTRIBUTE_SEVENTH';
export const SET_ATTRIBUTE_EIGHTH = 'SET_ATTRIBUTE_EIGHTH';
export const SET_PROFILE_PIC = 'SET_PROFILE_PIC';

//set user Id
export const GET_USER_ID = 'GET_USER_ID';

export const POST_SUCCESS = 'POST_SUCCESS';

//set profile data
export const GET_PROFILE_DATA = 'PROFILE_DATA';

//get profile Id
export const GET_PROFILE_ID_DATA = 'GET_PROFILE_ID_DATA';

// get searched data
export const GET_SEARCH_DATA = 'GET_SEARCH_DATA';

// reset searched Data
export const RESET_SEARCH_DATA = 'RESET_SEARCH_DATA';

// update chat contact view
export const CHAT_CONTACT = 'CHAT_CONTACT';

// refresh home page
export const REFRESH_HOME_PAGE = 'REFRESH_HOME_PAGE';

export const GET_CONVERSATION = 'GET_CONVERSATION';
export const GET_ALL_CONVERSATION = 'GET_ALL_CONVERSATION'


//reset loading
export const SET_SEARCH_LOADING = 'SET_SEARCH_LOADING';
export const SET_POST_PROFILE_LOADING = 'SET_POST_PROFILE_LOADING';
export const SET_UPDATE_PROFILE_LOADING = 'SET_UPDATE_PROFILE_LOADING';
export const SET_RETRIEVE_PROFILE_LOADING = 'SET_RETRIEVE_PROFILE_LOADING';
export const SET_ALL_PROFILE_LOADING = 'SET_ALL_PROFILE_LOADING';

//message loading
export const SET_MESSAGE_LOADING = 'SET_MESSAGE_LOADING';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const RESET_SEARCH_LOADING = 'RESET_SEARCH_LOADING';
export const RESET_AUTH_LOADING = 'RESET_AUTH_LOADING';